CRAWL_TARGETS = {
    "economy": [
        {
            "site": "NDRC",
            "name": "National Development and Reform Commission",
            "rss": None,
            "scrape_url": "https://www.ndrc.gov.cn/",
            "base_url": "https://www.ndrc.gov.cn",
            "link_selector": "a",
            "encoding": "utf-8",
            "filter_path": "/202",
        },
        {
            "site": "XINHUA_FIN",
            "name": "Xinhua Finance & Economy",
            "rss": "http://www.xinhuanet.com/fortune/news_fortune.xml",
            "base_url": "http://www.xinhuanet.com",
        },
        {
            "site": "MOFCOM",
            "name": "Ministry of Commerce",
            "rss": None,
            "scrape_url": "https://www.mofcom.gov.cn/xwfb/",
            "base_url": "https://www.mofcom.gov.cn",
            "link_selector": "a",
            "encoding": "utf-8",
            "filter_path": "/art/2026",
        },
    ],
    "technology": [
        {
            "site": "MIIT",
            "name": "Ministry of Industry and Information Technology",
            "rss": None,
            "scrape_url": "https://www.miit.gov.cn/xwdt/gxdt/lzyx/",
            "base_url": "https://www.miit.gov.cn",
            "link_selector": "ul li a, .list-content li a, .news-list li a",
            "encoding": "utf-8",
        },
        {
            "site": "CAC",
            "name": "Cyberspace Administration of China",
            "rss": None,
            "scrape_url": "https://www.cac.gov.cn/",
            "base_url": "https://www.cac.gov.cn",
            "link_selector": "a",
            "encoding": "utf-8",
            "filter_path": "/20",  # only links with date-based paths
        },
        {
            "site": "SASAC",
            "name": "State-owned Assets Supervision and Administration Commission",
            "rss": None,
            "scrape_url": "http://www.sasac.gov.cn/n2588025/n2588124/",
            "base_url": "http://www.sasac.gov.cn",
            "link_selector": "a",
            "encoding": "utf-8",
            "filter_path": "content.html",
        },
    ],
    "military": [
        {
            "site": "81CN",
            "name": "PLA Daily / China Military Online",
            "rss": None,
            "scrape_url": "http://www.81.cn/",
            "base_url": "http://www.81.cn",
            "link_selector": "a",
            "encoding": "utf-8",
            "filter_path": "81.cn",
        },
        {
            "site": "GLOBALTIMES_MIL",
            "name": "Global Times Military",
            "rss": "https://www.globaltimes.cn/rss/outbrain.xml",
            "base_url": "https://www.globaltimes.cn",
            "filter_keywords": ["military", "army", "navy", "air force", "missile", "weapon", "defense", "PLA", "troops"],
        },
        {
            "site": "GUANCHA",
            "name": "Guancha Syndicate",
            "rss": None,
            "scrape_url": "https://www.guancha.cn/military-affairs",
            "base_url": "https://www.guancha.cn",
            "link_selector": "div.feed-card-title a, .article-list li a, h3 a, a.title",
            "encoding": "utf-8",
        },
    ],
    "governance": [
        {
            "site": "GOVCH",
            "name": "State Council of the PRC",
            "rss": None,
            "scrape_url": "https://www.gov.cn/zhengce/zuixin/",
            "base_url": "https://www.gov.cn",
            "link_selector": "ul li a, .news-list li a, .list li a",
            "encoding": "utf-8",
        },
        {
            "site": "PEOPLE",
            "name": "People's Daily English",
            "rss": "http://en.people.cn/90002/90003/rss.xml",
            "base_url": "http://en.people.cn",
        },
        {
            "site": "NPC",
            "name": "National People's Congress",
            "rss": None,
            "scrape_url": "http://www.npc.gov.cn/npc/c2/c30834/",
            "base_url": "http://www.npc.gov.cn",
            "link_selector": "ul li a, .list li a, .news-list li a",
            "encoding": "utf-8",
        },
    ],
    "foreign_policy": [
        {
            "site": "MFA",
            "name": "Ministry of Foreign Affairs",
            "rss": None,
            "scrape_url": "https://www.fmprc.gov.cn/wjbzhd/",
            "base_url": "https://www.fmprc.gov.cn",
            "link_selector": "ul li a, .list-content li a, .news-list li a, div.list li a",
            "encoding": "utf-8",
        },
        {
            "site": "XINHUA",
            "name": "Xinhua News Agency English",
            "rss": "https://feeds.feedburner.com/NewHuaNetEnglishNewsHeadlines",
            "base_url": "http://www.xinhuanet.com",
        },
        {
            "site": "GLOBALTIMES",
            "name": "Global Times",
            "rss": "https://www.globaltimes.cn/rss/outbrain.xml",
            "base_url": "https://www.globaltimes.cn",
        },
        {
            "site": "CGTN",
            "name": "CGTN English",
            "rss": "https://www.cgtn.com/subscribe/rss/section/world.xml",
            "base_url": "https://www.cgtn.com",
        },
    ],
}

DOMAIN_LABELS = {
    "economy": "Economy",
    "technology": "Technology",
    "military": "Military",
    "governance": "Local & Governance",
    "foreign_policy": "Foreign Policy",
}

DOMAIN_COLORS = {
    "economy": "#2563eb",
    "technology": "#7c3aed",
    "military": "#dc2626",
    "governance": "#059669",
    "foreign_policy": "#d97706",
}
